### ISSUE TITLE
&quot; gets re-encoded

### ISSUE THREAD

**Issue by antimatter15** [cramforce/streamie#12]
Some people post with some client that uses &quot; instead of " and streamie annoyingly html-encodes the already html-ified stuff.

**Comment by cramforce** [comment]
Yeah, I've noticed as well. This is quite weird, because it seems to be limited to only very few clients. That said I dont really know what to do. < and > are always encoded in tweets. Thats why I reverse that before actual HTML encoding. I can't simply to s/&quot;/"/g though, because not all clients encode it (neither do they encode & I think).

I guess we have to come up with a rule for when to do it or as a last resort look at the twitter client name.

**Comment by cramforce** [comment]
Hmm, will now decode it always.
